### ISSUE TITLE
Editing or even buying a product generates redirects to other products

### ISSUE THREAD

**Issue by nikobcn** [yasglobal/permalinks-customizer#17]
Hello, 

We ran into an issue with v2.2.0, basically after editing stock of a product, or even after a simple buy from one of our client (thus editing the product's stock) multiple redirects are created, and one product can be pointed at by multiple products. 

Before : 
Product A --> Single product page A
Product B --> Single product page B
Product C --> Single product page C
Product D --> Single product page D

After : 
Product A --> Single product page A
Product B --> Single product page A
Product C --> Single product page A
Product D --> Single product page A

WooCommerce is v3.3.3, WordPress 4.9.8

We are going to try v2.3.0 to see if the issue persists.

Best,

NG

**Comment by samiahmedsiddiqui** [comment]
Hi @nikobcn 

Issue which you are pointing is already resolved in v2.2.0. Not sure what's scenario remaining. Please let me know once you tested on the updated version.

Thanks,
Sami

**Comment by nikobcn** [comment]
I've added the two filters in our functions.php for, hoping for automatic and random redirect to stop.
Until yesterday we were running v2.2.0, and I can assure you random redirects on purchase were still frequent occurrences.

Otherwise the plug-in is great and we hope we'll be able to still use it. But random redirections when you feel with fifty sales in twenty minutes aren't an option.

Now running 2.3.0, plus the filters, we will see what happens

Best,

NG

On Oct 16, 2018 08:13, Sami Ahmed Siddiqui <notifications@github.com> wrote:

Hi @nikobcn<https://github.com/nikobcn>

Issue which you are pointing is already resolved in v2.2.0. Not sure what's scenario remaining. Please let me know once you tested on the updated version.

Thanks,
Sami

**Comment by samiahmedsiddiqui** [comment]
@nikobcn Once you added the Filter then the redirects won't be created anymore either in `v2.2.0` or the latest version `2.3.1`.

As you said that you are facing this issue with purchase type so, i'll give it a look for that.

Thanks,
Sami

**Comment by nikobcn** [comment]
Hello @samiahmedsiddiqui  

Adding the filters didn't fix the issue. 
Yesterday night we had a **sale on Product X**, and here is the situation as of today, without correcting or editing anything:

**1** - **No redirects have been created** under "/wp-admin/admin.php?page=permalinks-customizer-redirects"
**2** - When **rollover product Y**, the URL showing below is the correct one. 
**3** - **Same** goes with **product X**. BUT
**4** - When **clicked on, Y shows product X**, with, in the browser's address bar product Y's URL.
**5** - When **clicked on, X shows product X**, with, in the browser's address bar product Y's URL.

Conclusions:
**A** - **Event 4** makes me think that there are still redirections going on at some level
**B** - **Conclusion A** makes me think that redirects were symptoms of some URL-rewriting going on during the selling process, and that blocking redirect creations just prevented the symptoms, not the cause.
**C** - We are going to research more with other plugins in charge of redirecting the trafic. See if any conflicts can occur. Please keep us posting, next big sale is Wednesday and we have to be ready.

Thanks
N.

**Comment by samiahmedsiddiqui** [comment]
@nikobcn Which 2 filters have you added previously? 

If you added these 2 filters: 
`
add_filter( 'permalinks_customizer_auto_created_redirects', '__return_false');
`
`
add_filter( 'permalinks_customizer_disable_redirects', '__return_false');
`

then Redirects won't be created and worked from the Plugin. Looks like that there is some conflict with anything.

Regards,
Sami

**Comment by samiahmedsiddiqui** [comment]
@nikobcn Which 2 filters have you added previously? 

If you added these 2 filters: 
`
add_filter( 'permalinks_customizer_auto_created_redirects', '__return_false');
add_filter( 'permalinks_customizer_disable_redirects', '__return_false');
`

then Redirects won't be created and worked from the Plugin. Looks like that there is some conflict with anything.

Regards,
Sami

**Comment by nikobcn** [comment]
Thanks for you quick answer @samiahmedsiddiqui ,

Point is, redirects were due to URL editing / changes, not caused by a human user, but by sales. Redirects were just a symptom of those random changes in URLs. The changes are still there, the filters just prevent the redirect creation consequence.

So we still have something editing the URLs on each sale.

Best,
N.

**Comment by samiahmedsiddiqui** [comment]
`
add_filter( 'permalinks_customizer_disable_redirects', '__return_false');
`

This filter means that the created redirects won't be worked anymore. If you like the created redirects to be worked properly, you need to remove this filter.

I'll check the payment redirect issue and try to fix it out soon.

Thanks,
Sami

**Comment by nikobcn** [comment]
Great news. 
Thanks. To help you, we notices that the bug occurs on both sale or editing stocks, indicating that it could be related with stock editing.

Best,

N.

**Comment by samiahmedsiddiqui** [comment]
@nikobcn I have tried but not able to create the issue on my end. If you don't mind so could you help me on figuring this issue?

Thanks,
Sami

**Comment by samiahmedsiddiqui** [comment]
As per not getting any response so closing this. If someone finds any issue feel free to create a new issue.
